# Повний і правильний вміст для netlify.toml

[build]
  # Цей рядок вказує Netlify, що код функцій знаходиться в папці "functions"
  functions = "functions/"

# Цей блок створює правило перенаправлення
[[redirects]]
  # Усі запити, що починаються з /api/
  from = "/api/*"
  # Будуть перенаправлені на відповідну функцію
  to = "/.netlify/functions/:splat"
  # Зі статусом 200 (ОК), що означає, що це не звичайний редірект, а проксі-запит
  status = 200
